import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import * as XLSX from "xlsx";

export async function GET() {
  const session = await auth();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    // Fetch ALL parts with full details (including zero-stock)
    const parts = await prisma.part.findMany({
      include: {
        category: true,
        subcategory: true,
        hsn_code: true,
        stock_entries: {
          include: { location: true }
        }
      },
      orderBy: [{ category: { name: "asc" } }, { name: "asc" }]
    });

    // Fetch ALL stock movements (comprehensive)
    const movements = await prisma.stockMovement.findMany({
      include: {
        part: { include: { category: true } },
        from_location: true,
        to_location: true,
        user: true
      },
      orderBy: { performed_at: "desc" }
    });

    const cleanLabel = (label: string) =>
      label
        .split(" > ")
        .filter(p => !p.toLowerCase().includes("default shelf") && !p.toLowerCase().includes("default bin"))
        .join(" > ");

    // ── Sheet 1: Summary ─────────────────────────────────────────────────────
    const totalQty = parts.reduce((s, p) => s + p.stock_entries.reduce((ss, e) => ss + e.quantity, 0), 0);
    const inStock  = parts.filter(p => p.stock_entries.some(e => e.quantity > 0)).length;
    const zeroStock = parts.filter(p => p.stock_entries.length === 0 || p.stock_entries.every(e => e.quantity === 0)).length;

    const categoryMap: Record<string, { count: number; inStock: number; totalQty: number }> = {};
    for (const part of parts) {
      const cat = part.category.label;
      if (!categoryMap[cat]) categoryMap[cat] = { count: 0, inStock: 0, totalQty: 0 };
      categoryMap[cat].count++;
      const qty = part.stock_entries.reduce((s, e) => s + e.quantity, 0);
      categoryMap[cat].totalQty += qty;
      if (qty > 0) categoryMap[cat].inStock++;
    }

    const summaryRows = [
      { "Metric": "Report Generated On", "Value": new Date().toLocaleString("en-IN") },
      { "Metric": "Generated By", "Value": session.user.name },
      { "Metric": "", "Value": "" },
      { "Metric": "Total Parts Registered", "Value": parts.length },
      { "Metric": "Parts In Stock (qty > 0)", "Value": inStock },
      { "Metric": "Parts With Zero Stock", "Value": zeroStock },
      { "Metric": "Total Quantity (All Parts)", "Value": totalQty },
      { "Metric": "Total Stock Movements", "Value": movements.length },
      { "Metric": "", "Value": "" },
      { "Metric": "=== CATEGORY BREAKDOWN ===", "Value": "" },
      ...Object.entries(categoryMap).map(([cat, d]) => ({
        "Metric": cat,
        "Value": `${d.count} parts | ${d.inStock} in stock | ${d.totalQty} units total`
      }))
    ];

    // ── Sheet 2: Stock Inventory (ALL parts, including zero stock) ────────────
    const inventoryRows: any[] = [];
    for (const part of parts) {
      const totalPartQty = part.stock_entries.reduce((s, e) => s + e.quantity, 0);
      const stockStatus = totalPartQty === 0 ? "OUT OF STOCK" : part.stock_entries.some(e => e.min_quantity !== null && e.quantity < e.min_quantity!) ? "LOW STOCK" : "IN STOCK";

      if (part.stock_entries.length === 0) {
        inventoryRows.push({
          "Part Name": part.name,
          "Part Number": part.part_number || "-",
          "Category": part.category.label,
          "Sub-Category": part.subcategory?.label || "-",
          "Package": part.package || "-",
          "HSN Code": part.hsn_code.code,
          "Stock Status": "OUT OF STOCK",
          "Location Zone": "-",
          "Location": "-",
          "Location ID (Short)": "-",
          "Quantity": 0,
          "Unit": "pcs",
          "Min Qty Alert": "-",
          "Total Qty (This Part)": 0,
          "Price/Unit (₹)": part.price_per_unit ?? "-",
          "Total Value (₹)": "-",
          "Purchase Link": part.purchase_url || "-",
          "Datasheet URL": part.datasheet_url || "-",
          "Comments / Specs": part.comment || "-"
        });
      } else {
        for (const entry of part.stock_entries) {
          const totalValue = part.price_per_unit ? (part.price_per_unit * entry.quantity).toFixed(2) : "-";
          inventoryRows.push({
            "Part Name": part.name,
            "Part Number": part.part_number || "-",
            "Category": part.category.label,
            "Sub-Category": part.subcategory?.label || "-",
            "Package": part.package || "-",
            "HSN Code": part.hsn_code.code,
            "Stock Status": stockStatus,
            "Location Zone": entry.location.zone,
            "Location": cleanLabel(entry.location.label),
            "Location ID (Short)": entry.location.id.slice(-8),
            "Quantity": entry.quantity,
            "Unit": entry.unit,
            "Min Qty Alert": entry.min_quantity ?? "-",
            "Total Qty (This Part)": totalPartQty,
            "Price/Unit (₹)": part.price_per_unit ?? "-",
            "Total Value (₹)": totalValue,
            "Purchase Link": part.purchase_url || "-",
            "Datasheet URL": part.datasheet_url || "-",
            "Comments / Specs": part.comment || "-"
          });
        }
      }
    }

    // ── Sheet 3: Stock Movements (full history) ───────────────────────────────
    const movementTypeLabel: Record<string, string> = {
      IN: "Stock IN (Received)",
      OUT: "Stock OUT (Dispatched)",
      TRANSFER: "Transfer (Location Change)",
      ADJUSTMENT: "Inventory Adjustment"
    };

    const movementRows = movements.map(m => {
      const dateStr = new Date(m.performed_at).toLocaleString("en-IN");
      return {
        "Date & Time": dateStr,
        "Part Name": m.part.name,
        "Category": m.part.category.label,
        "Movement Type": movementTypeLabel[m.movement_type] || m.movement_type,
        "Quantity": m.quantity,
        "From Location": m.from_location ? cleanLabel(m.from_location.label) : "-",
        "To Location": m.to_location ? cleanLabel(m.to_location.label) : "-",
        "Reference No.": m.reference || "-",
        "Notes": m.notes || "-",
        "Performed By": m.user.name
      };
    });

    // ── Build Workbook ────────────────────────────────────────────────────────
    const wb = XLSX.utils.book_new();

    const wsSummary = XLSX.utils.json_to_sheet(summaryRows);
    wsSummary["!cols"] = [{ wch: 40 }, { wch: 45 }];
    XLSX.utils.book_append_sheet(wb, wsSummary, "Summary");

    const wsInventory = XLSX.utils.json_to_sheet(inventoryRows);
    wsInventory["!cols"] = [
      { wch: 32 }, { wch: 14 }, { wch: 13 }, { wch: 13 }, { wch: 10 },
      { wch: 10 }, { wch: 14 }, { wch: 12 }, { wch: 26 }, { wch: 14 },
      { wch: 10 }, { wch: 6 }, { wch: 12 }, { wch: 16 },
      { wch: 14 }, { wch: 14 }, { wch: 40 }, { wch: 40 }, { wch: 35 }
    ];
    XLSX.utils.book_append_sheet(wb, wsInventory, "Stock Inventory");

    const wsMovements = XLSX.utils.json_to_sheet(movementRows);
    wsMovements["!cols"] = [
      { wch: 20 }, { wch: 32 }, { wch: 13 }, { wch: 22 }, { wch: 10 },
      { wch: 26 }, { wch: 26 }, { wch: 16 }, { wch: 30 }, { wch: 18 }
    ];
    XLSX.utils.book_append_sheet(wb, wsMovements, "Stock Movements");

    // ── Return Excel file ─────────────────────────────────────────────────────
    const buf = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
    const dateStr = new Date().toISOString().slice(0, 10);

    return new NextResponse(buf, {
      status: 200,
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": `attachment; filename="SeculogixInStock_${dateStr}.xlsx"`,
        "Content-Length": buf.length.toString()
      }
    });
  } catch (error) {
    console.error("Export error:", error);
    return NextResponse.json({ error: (error as any).message }, { status: 500 });
  }
}
